=== MutahirAhmed1/AI-202409D2TTS/json/images/external.dtd
<!ELEMENT aptech (staff*,students*)>
<!ELEMENT staff (id , name , email)>
<!ELEMENT students (id,name,course)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>

"aptech shahrah-e-faisal">

=== MutahirAhmed1/AI-202409D2TTS/json/images/external.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aptech SYSTEM "external.dtd"> 
<aptech>
    
<staff department="HR">
    <id></id>
    <name></name>
    <email></email>
    </staff>
    <staff department="HR">
        <id></id>
        <name></name>
        <email></email>
        </staff>
    <students>
        <id></id>
        <name></name>
        <course></course>
    </students>
</aptech>
