<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE aptech [
    <!ELEMENT aptech (students , employee)>
    <!ELEMENT students (id,name,email)>
    <!ELEMENT employee (id,name,salary)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT salary (#PCDATA)>
]>
<aptech>
    <students>
        <id></id>
        <name></name>
        <email></email>
    </students>

    

    <employee>
        <id></id>
        <name></name>
        <salary></salary>
    </employee>
</aptech>